//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_bom_detail_update_view
    {
        public int bdid { get; set; }
        public string bom_no { get; set; }
        public string part_no { get; set; }
        public string mt_no { get; set; }
        public Nullable<decimal> lot_pct { get; set; }
        public string step_cd { get; set; }
        public string item_cd { get; set; }
        public Nullable<decimal> csp { get; set; }
        public string feed_unit { get; set; }
        public string div_cd { get; set; }
        public Nullable<int> chg_ver { get; set; }
        public string chg_cd { get; set; }
        public string remark { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public Nullable<System.DateTime> reg_dt { get; set; }
        public string chg_id { get; set; }
        public Nullable<System.DateTime> chg_dt { get; set; }
        public string id { get; set; }
    }
}
