//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_bom_part_info_interface_view
    {
        public string bom_no2 { get; set; }
        public string part_no2 { get; set; }
        public string step_cd { get; set; }
        public int bpid { get; set; }
        public string bom_no { get; set; }
        public string part_no { get; set; }
        public string part_nm { get; set; }
        public string mt_no { get; set; }
        public Nullable<int> need_time { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public Nullable<System.DateTime> reg_dt { get; set; }
        public string chg_id { get; set; }
        public Nullable<System.DateTime> chg_dt { get; set; }
    }
}
