//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_line_process_info_interface
    {
        public int dlpid { get; set; }
        public string line_no { get; set; }
        public string process_no { get; set; }
        public string process_nm { get; set; }
        public string process_type { get; set; }
        public string prounit_cd { get; set; }
        public string item_vcd { get; set; }
        public string bom_no { get; set; }
        public string qc_range_cd { get; set; }
        public Nullable<int> need_time { get; set; }
        public Nullable<decimal> man_num { get; set; }
        public string color { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
        public string photo_file { get; set; }
    }
}
