//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_machine_info
    {
        public int mno { get; set; }
        public string mc_type { get; set; }
        public string mc_no { get; set; }
        public string mc_nm { get; set; }
        public string purpose { get; set; }
        public string color { get; set; }
        public string barcode { get; set; }
        public string re_mark { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
        public string mc_erp { get; set; }
        public string mc_model { get; set; }
        public string mc_mfc { get; set; }
        public Nullable<int> mc_amt { get; set; }
        public System.DateTime is_dt { get; set; }
        public string mc_lct { get; set; }
        public string mc_prc { get; set; }
        public string full_mc { get; set; }
        public string label_mc { get; set; }
        public Nullable<int> voltage { get; set; }
        public Nullable<decimal> mc_pow { get; set; }
        public Nullable<int> mc_wgt { get; set; }
        public string mc_spec { get; set; }
        public string mc_plc { get; set; }
        public string sp_code { get; set; }
        public string mc_contact { get; set; }
    }
}
