//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_pro_unit
    {
        public int puid { get; set; }
        public string prounit_cd { get; set; }
        public string prounit_nm { get; set; }
        public string mc_type { get; set; }
        public string process_sts_cd { get; set; }
        public string process_sts_dt { get; set; }
        public string lct_cd { get; set; }
        public string color { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
