//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_style_info_interface
    {
        public int sid { get; set; }
        public string style_no { get; set; }
        public string style_cust_no { get; set; }
        public string style_nm { get; set; }
        public string style_vn_nm { get; set; }
        public string wh_nm { get; set; }
        public string buyer_nm { get; set; }
        public string ivtr_type { get; set; }
        public string routing { get; set; }
        public string prd_unit { get; set; }
        public Nullable<decimal> s_length { get; set; }
        public Nullable<decimal> s_width { get; set; }
        public Nullable<decimal> s_height { get; set; }
        public Nullable<decimal> s_top { get; set; }
        public Nullable<int> case_pcs_qty { get; set; }
        public Nullable<decimal> c_length { get; set; }
        public Nullable<decimal> c_width { get; set; }
        public Nullable<decimal> c_height { get; set; }
        public Nullable<decimal> c_cbm { get; set; }
        public string prd_group { get; set; }
        public string prd_ctgr { get; set; }
        public string prd_brand { get; set; }
        public string prd_app { get; set; }
        public string fsc_type { get; set; }
        public string fsc_prd_type { get; set; }
        public string fsc_group { get; set; }
        public string ivt_group_08 { get; set; }
        public string ivt_group_09 { get; set; }
        public string ivt_group_10 { get; set; }
        public Nullable<decimal> s_weight { get; set; }
        public string s_weight_unit { get; set; }
        public Nullable<decimal> s_weight_ratio { get; set; }
        public Nullable<decimal> s_volume { get; set; }
        public string s_volume_unit { get; set; }
        public Nullable<decimal> s_surface { get; set; }
        public string s_surface_unit { get; set; }
        public Nullable<decimal> s_tolerance { get; set; }
        public Nullable<decimal> s_leadtime { get; set; }
        public string md_cd { get; set; }
        public string prj_nm { get; set; }
        public string ssver { get; set; }
        public string part_nm { get; set; }
        public string standard { get; set; }
        public string cust_rev { get; set; }
        public string order_num { get; set; }
        public Nullable<int> pack_amt { get; set; }
        public string cav { get; set; }
        public string bom_type { get; set; }
        public string tds_no { get; set; }
        public string item_vcd { get; set; }
        public string qc_range_cd { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
