//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class snkdbEntities : DbContext
    {
        public snkdbEntities()
            : base("name=snkdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<author_info> author_info { get; set; }
        public DbSet<author_menu_info> author_menu_info { get; set; }
        public DbSet<buyer_info> buyer_info { get; set; }
        public DbSet<buyer_info_interface> buyer_info_interface { get; set; }
        public DbSet<comm_dt> comm_dt { get; set; }
        public DbSet<comm_mt> comm_mt { get; set; }
        public DbSet<d_bobbin_info> d_bobbin_info { get; set; }
        public DbSet<d_bobbin_lct_hist> d_bobbin_lct_hist { get; set; }
        public DbSet<d_bom_detail> d_bom_detail { get; set; }
        public DbSet<d_bom_detail_copy> d_bom_detail_copy { get; set; }
        public DbSet<d_bom_detail_interface> d_bom_detail_interface { get; set; }
        public DbSet<d_bom_info> d_bom_info { get; set; }
        public DbSet<d_bom_part_info> d_bom_part_info { get; set; }
        public DbSet<d_box_info> d_box_info { get; set; }
        public DbSet<d_line_info> d_line_info { get; set; }
        public DbSet<d_line_info_interface> d_line_info_interface { get; set; }
        public DbSet<d_line_mc_info> d_line_mc_info { get; set; }
        public DbSet<d_line_next_process> d_line_next_process { get; set; }
        public DbSet<d_line_process_info> d_line_process_info { get; set; }
        public DbSet<d_line_process_info_interface> d_line_process_info_interface { get; set; }
        public DbSet<d_line_unit_info> d_line_unit_info { get; set; }
        public DbSet<d_machine_info> d_machine_info { get; set; }
        public DbSet<d_machine_infoxxx> d_machine_infoxxx { get; set; }
        public DbSet<d_material_info> d_material_info { get; set; }
        public DbSet<d_material_info_copy> d_material_info_copy { get; set; }
        public DbSet<d_material_info_copy_28_04> d_material_info_copy_28_04 { get; set; }
        public DbSet<d_material_info_interface> d_material_info_interface { get; set; }
        public DbSet<d_material_info_temp> d_material_info_temp { get; set; }
        public DbSet<d_material_lct_hist> d_material_lct_hist { get; set; }
        public DbSet<d_model_info> d_model_info { get; set; }
        public DbSet<d_mold_info> d_mold_info { get; set; }
        public DbSet<d_pro_unit> d_pro_unit { get; set; }
        public DbSet<d_pro_unit_mc> d_pro_unit_mc { get; set; }
        public DbSet<d_pro_unit_staff> d_pro_unit_staff { get; set; }
        public DbSet<d_style_detail> d_style_detail { get; set; }
        public DbSet<d_style_detail_interface> d_style_detail_interface { get; set; }
        public DbSet<d_style_info> d_style_info { get; set; }
        public DbSet<d_style_info_interface> d_style_info_interface { get; set; }
        public DbSet<d_tray_info> d_tray_info { get; set; }
        public DbSet<date_ymd> date_ymd { get; set; }
        public DbSet<department_info> department_info { get; set; }
        public DbSet<equipment_info> equipment_info { get; set; }
        public DbSet<file_info> file_info { get; set; }
        public DbSet<interface_info> interface_info { get; set; }
        public DbSet<lct_info> lct_info { get; set; }
        public DbSet<lct_info_copy> lct_info_copy { get; set; }
        public DbSet<m_board> m_board { get; set; }
        public DbSet<m_display_issue> m_display_issue { get; set; }
        public DbSet<m_display_policy> m_display_policy { get; set; }
        public DbSet<m_display_policydetail> m_display_policydetail { get; set; }
        public DbSet<m_facline_qc> m_facline_qc { get; set; }
        public DbSet<m_facline_qc_value> m_facline_qc_value { get; set; }
        public DbSet<m_layout_dt> m_layout_dt { get; set; }
        public DbSet<m_layout_mt> m_layout_mt { get; set; }
        public DbSet<m_line_info> m_line_info { get; set; }
        public DbSet<m_order_facline_day> m_order_facline_day { get; set; }
        public DbSet<m_order_facline_dayhist> m_order_facline_dayhist { get; set; }
        public DbSet<m_order_facline_daytime> m_order_facline_daytime { get; set; }
        public DbSet<m_order_facline_detail> m_order_facline_detail { get; set; }
        public DbSet<m_order_facline_info> m_order_facline_info { get; set; }
        public DbSet<m_order_facline_info_old> m_order_facline_info_old { get; set; }
        public DbSet<m_order_facline_process> m_order_facline_process { get; set; }
        public DbSet<m_order_facline_qc> m_order_facline_qc { get; set; }
        public DbSet<m_order_facline_sim> m_order_facline_sim { get; set; }
        public DbSet<m_order_facsim_info> m_order_facsim_info { get; set; }
        public DbSet<m_time_sync> m_time_sync { get; set; }
        public DbSet<m_tot_inspect_dt> m_tot_inspect_dt { get; set; }
        public DbSet<m_tot_inspect_mt> m_tot_inspect_mt { get; set; }
        public DbSet<m_work_order> m_work_order { get; set; }
        public DbSet<manufac_info> manufac_info { get; set; }
        public DbSet<mb_author_info> mb_author_info { get; set; }
        public DbSet<mb_info> mb_info { get; set; }
        public DbSet<mb_info_2> mb_info_2 { get; set; }
        public DbSet<mb_info_copy> mb_info_copy { get; set; }
        public DbSet<mb_lct_info> mb_lct_info { get; set; }
        public DbSet<mb_message> mb_message { get; set; }
        public DbSet<menu_info> menu_info { get; set; }
        public DbSet<migration> migrations { get; set; }
        public DbSet<model_info> model_info { get; set; }
        public DbSet<model_part_info> model_part_info { get; set; }
        public DbSet<model_ref_info> model_ref_info { get; set; }
        public DbSet<notice_board> notice_board { get; set; }
        public DbSet<p_mpo_detail> p_mpo_detail { get; set; }
        public DbSet<p_mpo_detail_2> p_mpo_detail_2 { get; set; }
        public DbSet<p_mpo_detail_3> p_mpo_detail_3 { get; set; }
        public DbSet<p_mpo_info> p_mpo_info { get; set; }
        public DbSet<p_mpo_info_2> p_mpo_info_2 { get; set; }
        public DbSet<p_mpo_info_3> p_mpo_info_3 { get; set; }
        public DbSet<p_mpo_qc> p_mpo_qc { get; set; }
        public DbSet<p_mpo_qc_value> p_mpo_qc_value { get; set; }
        public DbSet<p_mpo_return> p_mpo_return { get; set; }
        public DbSet<p_mpo_sub> p_mpo_sub { get; set; }
        public DbSet<photo_info> photo_info { get; set; }
        public DbSet<qc_item_mt> qc_item_mt { get; set; }
        public DbSet<qc_itemcheck_dt> qc_itemcheck_dt { get; set; }
        public DbSet<qc_itemcheck_mt> qc_itemcheck_mt { get; set; }
        public DbSet<s_order_cutting_day> s_order_cutting_day { get; set; }
        public DbSet<s_order_cutting_dayhist> s_order_cutting_dayhist { get; set; }
        public DbSet<s_order_cutting_daytime> s_order_cutting_daytime { get; set; }
        public DbSet<s_order_cutting_detail> s_order_cutting_detail { get; set; }
        public DbSet<s_order_cutting_info> s_order_cutting_info { get; set; }
        public DbSet<s_order_cutting_master> s_order_cutting_master { get; set; }
        public DbSet<s_order_cutting_qc> s_order_cutting_qc { get; set; }
        public DbSet<s_order_cutting_qc_value> s_order_cutting_qc_value { get; set; }
        public DbSet<s_order_factory_detail> s_order_factory_detail { get; set; }
        public DbSet<s_order_factory_info> s_order_factory_info { get; set; }
        public DbSet<s_order_factory_master> s_order_factory_master { get; set; }
        public DbSet<s_order_info> s_order_info { get; set; }
        public DbSet<s_order_info_copy_13> s_order_info_copy_13 { get; set; }
        public DbSet<s_order_info_copy_29_04> s_order_info_copy_29_04 { get; set; }
        public DbSet<s_order_info_test> s_order_info_test { get; set; }
        public DbSet<s_order_info_test2> s_order_info_test2 { get; set; }
        public DbSet<s_order_master> s_order_master { get; set; }
        public DbSet<s_order_master_copy_28042020> s_order_master_copy_28042020 { get; set; }
        public DbSet<s_order_master_interface> s_order_master_interface { get; set; }
        public DbSet<s_order_ship_info> s_order_ship_info { get; set; }
        public DbSet<s_order_ship_master> s_order_ship_master { get; set; }
        public DbSet<supplier_info> supplier_info { get; set; }
        public DbSet<supplier_info_interface> supplier_info_interface { get; set; }
        public DbSet<sync_log> sync_log { get; set; }
        public DbSet<sync_log_dt> sync_log_dt { get; set; }
        public DbSet<tmp> tmps { get; set; }
        public DbSet<user_author> user_author { get; set; }
        public DbSet<w_box_mapping> w_box_mapping { get; set; }
        public DbSet<w_box_public> w_box_public { get; set; }
        public DbSet<w_dbox_mapping> w_dbox_mapping { get; set; }
        public DbSet<w_dtray_mapping> w_dtray_mapping { get; set; }
        public DbSet<w_enviro_hist> w_enviro_hist { get; set; }
        public DbSet<w_enviro_mt> w_enviro_mt { get; set; }
        public DbSet<w_lbox_dt> w_lbox_dt { get; set; }
        public DbSet<w_lbox_hist> w_lbox_hist { get; set; }
        public DbSet<w_lbox_info> w_lbox_info { get; set; }
        public DbSet<w_lbox_type> w_lbox_type { get; set; }
        public DbSet<w_material_info> w_material_info { get; set; }
        public DbSet<w_material_info_copy> w_material_info_copy { get; set; }
        public DbSet<w_material_lct_hist> w_material_lct_hist { get; set; }
        public DbSet<w_material_map_mc> w_material_map_mc { get; set; }
        public DbSet<w_material_map_staff> w_material_map_staff { get; set; }
        public DbSet<w_material_mapping> w_material_mapping { get; set; }
        public DbSet<w_mpo_hist> w_mpo_hist { get; set; }
        public DbSet<w_mr_detail> w_mr_detail { get; set; }
        public DbSet<w_mr_info> w_mr_info { get; set; }
        public DbSet<w_policy_mt> w_policy_mt { get; set; }
        public DbSet<w_pr_sms_detail> w_pr_sms_detail { get; set; }
        public DbSet<w_pr_sms_info> w_pr_sms_info { get; set; }
        public DbSet<w_product_info> w_product_info { get; set; }
        public DbSet<w_product_inspect> w_product_inspect { get; set; }
        public DbSet<w_product_inspect_value> w_product_inspect_value { get; set; }
        public DbSet<w_product_lct_hist> w_product_lct_hist { get; set; }
        public DbSet<w_product_lot_info> w_product_lot_info { get; set; }
        public DbSet<w_product_map_mc> w_product_map_mc { get; set; }
        public DbSet<w_product_map_staff> w_product_map_staff { get; set; }
        public DbSet<w_product_mapping> w_product_mapping { get; set; }
        public DbSet<w_product_qc> w_product_qc { get; set; }
        public DbSet<w_product_qc_value> w_product_qc_value { get; set; }
        public DbSet<w_psd_detail> w_psd_detail { get; set; }
        public DbSet<w_psd_info> w_psd_info { get; set; }
        public DbSet<w_psdpd_list> w_psdpd_list { get; set; }
        public DbSet<w_pvt_dt> w_pvt_dt { get; set; }
        public DbSet<w_pvt_mt> w_pvt_mt { get; set; }
        public DbSet<w_rd_detail> w_rd_detail { get; set; }
        public DbSet<w_rd_info> w_rd_info { get; set; }
        public DbSet<w_rdmt_list> w_rdmt_list { get; set; }
        public DbSet<w_sbox_dt> w_sbox_dt { get; set; }
        public DbSet<w_sbox_info> w_sbox_info { get; set; }
        public DbSet<w_sbox_type> w_sbox_type { get; set; }
        public DbSet<w_sd_detail> w_sd_detail { get; set; }
        public DbSet<w_sd_info> w_sd_info { get; set; }
        public DbSet<w_sdmt_list> w_sdmt_list { get; set; }
        public DbSet<w_vt_dt> w_vt_dt { get; set; }
        public DbSet<w_vt_mt> w_vt_mt { get; set; }
        public DbSet<w_wip_return> w_wip_return { get; set; }
        public DbSet<w_worktime_ymd> w_worktime_ymd { get; set; }
        public DbSet<webpages_membership> webpages_membership { get; set; }
        public DbSet<webpages_oauthmembership> webpages_oauthmembership { get; set; }
        public DbSet<buyer_info_insert_view> buyer_info_insert_view { get; set; }
        public DbSet<buyer_info_update_view> buyer_info_update_view { get; set; }
        public DbSet<d_bom_detail_insert_view> d_bom_detail_insert_view { get; set; }
        public DbSet<d_bom_detail_update_view> d_bom_detail_update_view { get; set; }
        public DbSet<d_bom_info_insert_view> d_bom_info_insert_view { get; set; }
        public DbSet<d_bom_info_update_view> d_bom_info_update_view { get; set; }
        public DbSet<d_bom_part_info_insert_view> d_bom_part_info_insert_view { get; set; }
        public DbSet<d_bom_part_info_update_view> d_bom_part_info_update_view { get; set; }
        public DbSet<d_bom_part_info_view> d_bom_part_info_view { get; set; }
        public DbSet<d_material_info_interface_insert_view> d_material_info_interface_insert_view { get; set; }
        public DbSet<d_material_info_interface_view> d_material_info_interface_view { get; set; }
        public DbSet<d_material_info_view> d_material_info_view { get; set; }
        public DbSet<d_style_info_insert_view> d_style_info_insert_view { get; set; }
        public DbSet<d_style_info_update_view> d_style_info_update_view { get; set; }
        public DbSet<p_mpo_info_insert_view> p_mpo_info_insert_view { get; set; }
        public DbSet<p_mpo_info_update_view> p_mpo_info_update_view { get; set; }
        public DbSet<purchaseapproval_view> purchaseapproval_view { get; set; }
        public DbSet<purchaseapprovaldetail_view> purchaseapprovaldetail_view { get; set; }
        public DbSet<purchasescheduledetail> purchasescheduledetails { get; set; }
        public DbSet<purchasestatusdetail_view> purchasestatusdetail_view { get; set; }
        public DbSet<s_order_info_insert_view> s_order_info_insert_view { get; set; }
        public DbSet<s_order_info_update_view> s_order_info_update_view { get; set; }
        public DbSet<s_order_master_insert_view> s_order_master_insert_view { get; set; }
        public DbSet<s_order_master_update_view> s_order_master_update_view { get; set; }
        public DbSet<supplier_info_insert_view> supplier_info_insert_view { get; set; }
        public DbSet<supplier_info_update_view> supplier_info_update_view { get; set; }
    }
}
