//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class snk_interfaceEntities : DbContext
    {
        public snk_interfaceEntities()
            : base("name=snk_interfaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<buyer_info_interface> buyer_info_interface { get; set; }
        public DbSet<d_bom_detail_interface> d_bom_detail_interface { get; set; }
        public DbSet<d_bom_detail_interface_copy> d_bom_detail_interface_copy { get; set; }
        public DbSet<d_bom_detail_interface_copy_copy> d_bom_detail_interface_copy_copy { get; set; }
        public DbSet<d_bom_info_interface> d_bom_info_interface { get; set; }
        public DbSet<d_bom_info_interface_29062020> d_bom_info_interface_29062020 { get; set; }
        public DbSet<d_bom_info_interface_copy> d_bom_info_interface_copy { get; set; }
        public DbSet<d_bom_part_info_interface> d_bom_part_info_interface { get; set; }
        public DbSet<d_bom_part_info_interface_copy> d_bom_part_info_interface_copy { get; set; }
        public DbSet<d_bom_part_info_interface_copy2> d_bom_part_info_interface_copy2 { get; set; }
        public DbSet<d_line_info_interface> d_line_info_interface { get; set; }
        public DbSet<d_line_process_info_interface> d_line_process_info_interface { get; set; }
        public DbSet<d_material_info_interface> d_material_info_interface { get; set; }
        public DbSet<d_style_detail_interface> d_style_detail_interface { get; set; }
        public DbSet<d_style_info_interface> d_style_info_interface { get; set; }
        public DbSet<interface_info> interface_info { get; set; }
        public DbSet<mb_info_interface> mb_info_interface { get; set; }
        public DbSet<p_mpo_detail_interface> p_mpo_detail_interface { get; set; }
        public DbSet<p_mpo_detail_interface_copy2> p_mpo_detail_interface_copy2 { get; set; }
        public DbSet<p_mpo_info_interface> p_mpo_info_interface { get; set; }
        public DbSet<p_mpo_info_interface_copy> p_mpo_info_interface_copy { get; set; }
        public DbSet<s_order_info_interface> s_order_info_interface { get; set; }
        public DbSet<s_order_master_interface> s_order_master_interface { get; set; }
        public DbSet<supplier_info_interface> supplier_info_interface { get; set; }
        public DbSet<d_bom_part_info_interface_view> d_bom_part_info_interface_view { get; set; }
        public DbSet<s_order_info_interface_view> s_order_info_interface_view { get; set; }
    }
}
