//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment_info
    {
        public int emno { get; set; }
        public string as_no { get; set; }
        public string as_cd { get; set; }
        public string as_nm { get; set; }
        public string srl_no { get; set; }
        public string mac_add { get; set; }
        public string sts_cd { get; set; }
        public string lct_cd { get; set; }
        public string lct_sts_cd { get; set; }
        public string mgm_dept_cd { get; set; }
        public string cost_dept_cd { get; set; }
        public string unit { get; set; }
        public Nullable<int> quantity { get; set; }
        public string mf_cd { get; set; }
        public string md_cd { get; set; }
        public string sp_cd { get; set; }
        public Nullable<int> eq_prc { get; set; }
        public string eq_prc_unit { get; set; }
        public string barcode { get; set; }
        public string dev_start_dt { get; set; }
        public string puchs_dt { get; set; }
        public string vailed_dt { get; set; }
        public string re_mark { get; set; }
        public string from_lct_cd { get; set; }
        public string to_lct_cd { get; set; }
        public string div_cd { get; set; }
        public string charge_id { get; set; }
        public string borrow_id { get; set; }
        public string return_id { get; set; }
        public string mgm_id { get; set; }
        public string receive_id { get; set; }
        public string output_dt { get; set; }
        public string input_dt { get; set; }
        public string disps_dt { get; set; }
        public string attach_cd { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
