//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_display_policydetail
    {
        public int mdid { get; set; }
        public string old_no { get; set; }
        public string policy_code { get; set; }
        public string policy_type { get; set; }
        public Nullable<int> doing_time { get; set; }
        public string use_yn { get; set; }
        public string re_mark { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
