//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_facline_qc
    {
        public int fqno { get; set; }
        public string fq_no { get; set; }
        public Nullable<int> oldhno { get; set; }
        public string fo_no { get; set; }
        public string po_no { get; set; }
        public string line_no { get; set; }
        public string process_no { get; set; }
        public string process_type { get; set; }
        public string prounit_cd { get; set; }
        public string work_dt { get; set; }
        public string item_vcd { get; set; }
        public string item_nm { get; set; }
        public string item_exp { get; set; }
        public Nullable<int> check_qty { get; set; }
        public Nullable<int> ok_qty { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
