//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_order_facline_sim
    {
        public int ofsno { get; set; }
        public string ofs_no { get; set; }
        public string fo_no { get; set; }
        public int qty_day_line { get; set; }
        public int line_qty { get; set; }
        public int day_qty { get; set; }
        public Nullable<decimal> need_day { get; set; }
        public Nullable<decimal> total_need_day { get; set; }
        public int fo_qty { get; set; }
        public string po_no { get; set; }
        public string lct_cd { get; set; }
        public string product_dt { get; set; }
        public string product_real_dt { get; set; }
        public string re_mark { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
