//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_order_facline_qc
    {
        public int qcno { get; set; }
        public Nullable<int> oldhno { get; set; }
        public string oldd_no { get; set; }
        public string old_no { get; set; }
        public string fo_no { get; set; }
        public string po_no { get; set; }
        public string process_no { get; set; }
        public string bom_no { get; set; }
        public string prounit_cd { get; set; }
        public string line_no { get; set; }
        public string work_dt { get; set; }
        public string prod_sts_cd { get; set; }
        public string w_val { get; set; }
        public string w_unit { get; set; }
        public string l_val { get; set; }
        public string l_unit { get; set; }
        public string qc_01 { get; set; }
        public string qc_02 { get; set; }
        public string qc_03 { get; set; }
        public string qc_04 { get; set; }
        public string photo_file { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
