//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_order_facline_daytime
    {
        public int olddtno { get; set; }
        public string olddt_no { get; set; }
        public string oldd_no { get; set; }
        public string prounit_cd { get; set; }
        public string line_no { get; set; }
        public string process_no { get; set; }
        public string process_type { get; set; }
        public string prod_sts_cd { get; set; }
        public string fo_no { get; set; }
        public string po_no { get; set; }
        public string bom_no { get; set; }
        public string work_ymd { get; set; }
        public string work_dt { get; set; }
        public Nullable<int> work_time { get; set; }
        public Nullable<int> work_no { get; set; }
        public string start_time { get; set; }
        public string end_time { get; set; }
        public Nullable<int> prod_qty { get; set; }
        public Nullable<int> done_qty { get; set; }
        public Nullable<int> move_qty { get; set; }
        public Nullable<int> refer_qty { get; set; }
        public string re_mark { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
