//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_order_facline_detail
    {
        public int oldno { get; set; }
        public string old_no { get; set; }
        public string fo_no { get; set; }
        public string po_no { get; set; }
        public string bom_no { get; set; }
        public string line_no { get; set; }
        public string process_no { get; set; }
        public string process_type { get; set; }
        public string prounit_cd { get; set; }
        public string status_cd { get; set; }
        public string start_dt { get; set; }
        public string stat_time { get; set; }
        public string end_dt { get; set; }
        public string end_time { get; set; }
        public Nullable<int> prounit_target_qty { get; set; }
        public Nullable<int> sked_qty { get; set; }
        public string material_check_yn { get; set; }
        public string machine_check_yn { get; set; }
        public string staff_check_yn { get; set; }
        public string re_mark { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
