//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class model_ref_info
    {
        public int mrno { get; set; }
        public string mf_cd { get; set; }
        public string md_cd { get; set; }
        public string ref_cd { get; set; }
        public string ref_nm { get; set; }
        public string file_nm { get; set; }
        public string file_url { get; set; }
        public string link_url { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
