//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class model_info
    {
        public int mdno { get; set; }
        public string mf_cd { get; set; }
        public string md_cd { get; set; }
        public string md_nm { get; set; }
        public string md_vn_nm { get; set; }
        public string prt_cd { get; set; }
        public string tp_cd { get; set; }
        public string group_cd { get; set; }
        public string func_cd { get; set; }
        public string photo_file { get; set; }
        public string dimension { get; set; }
        public string elect { get; set; }
        public string elect_unit_cd { get; set; }
        public string e_cst { get; set; }
        public string ecst_unit_cd { get; set; }
        public string wgt { get; set; }
        public string wgt_unit_cd { get; set; }
        public string re_mark { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
