//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class model_part_info
    {
        public int mpno { get; set; }
        public string mf_cd { get; set; }
        public string md_cd { get; set; }
        public string part_cd { get; set; }
        public string part_id { get; set; }
        public string part_nm { get; set; }
        public Nullable<int> part_prc { get; set; }
        public string prc_unit { get; set; }
        public string life_cycle { get; set; }
        public string lifec_unit { get; set; }
        public string pic_file { get; set; }
        public string re_mark { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
