//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_mpo_sub
    {
        public int psid { get; set; }
        public string mspo_no { get; set; }
        public string mdpo_no { get; set; }
        public string mt_no { get; set; }
        public string mt_cd { get; set; }
        public string md_sts_cd { get; set; }
        public string rec_input_dt { get; set; }
        public string exp_input_dt { get; set; }
        public Nullable<int> qr_qty { get; set; }
        public Nullable<int> gr_qty { get; set; }
        public string unit_gr_qty { get; set; }
        public Nullable<decimal> rec_qty { get; set; }
        public Nullable<int> rec_bundle_qty { get; set; }
        public Nullable<decimal> defect_qty { get; set; }
        public string def_reson_cd { get; set; }
        public string expiry_dt { get; set; }
        public Nullable<decimal> return_qty { get; set; }
        public string return_reson_cd { get; set; }
        public string waybill_file { get; set; }
        public string sp_cd { get; set; }
        public string lot_no { get; set; }
        public string public_cd { get; set; }
        public string voucher { get; set; }
        public string bundle_unit { get; set; }
        public string order_dt { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public Nullable<decimal> pass_qty { get; set; }
        public string reg_id { get; set; }
        public Nullable<System.DateTime> reg_dt { get; set; }
        public string chg_id { get; set; }
        public Nullable<System.DateTime> chg_dt { get; set; }
        public Nullable<int> rec_cnt { get; set; }
    }
}
