//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_mpo_return
    {
        public int mpid { get; set; }
        public string rt_no { get; set; }
        public Nullable<int> pdid { get; set; }
        public string mpo_no { get; set; }
        public string mdpo_no { get; set; }
        public string mt_no { get; set; }
        public string md_sts_cd { get; set; }
        public string lct_cd { get; set; }
        public Nullable<decimal> defect_qty { get; set; }
        public string def_reson_cd { get; set; }
        public Nullable<decimal> return_qty { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
        public string lct_sts_cd { get; set; }
    }
}
