//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class photo_info
    {
        public int pi { get; set; }
        public Nullable<int> mdii { get; set; }
        public string div_cd { get; set; }
        public string div_val { get; set; }
        public string photo_file { get; set; }
        public Nullable<int> doing_time { get; set; }
        public string use_yn { get; set; }
        public string re_mark { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
