//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseapproval_view
    {
        public long RowNum { get; set; }
        public string style_no { get; set; }
        public string bom_no { get; set; }
        public string style_nm { get; set; }
        public string sts_mt2 { get; set; }
        public int pmid { get; set; }
        public string mpo_no { get; set; }
        public string order_dt { get; set; }
        public string re_mark { get; set; }
        public string mpo_nm { get; set; }
        public string brand_no { get; set; }
        public string brand_nm { get; set; }
        public string po_sts { get; set; }
        public string sts_mt { get; set; }
        public string po_no { get; set; }
        public string purch_cd { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
        public string sp_cd { get; set; }
        public string sp_nm { get; set; }
        public Nullable<int> mpo_qty { get; set; }
        public string emp_no { get; set; }
        public string emp_nm { get; set; }
    }
}
