//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_order_factory_detail
    {
        public int fdno { get; set; }
        public string fo_no { get; set; }
        public string fm_no { get; set; }
        public string po_no { get; set; }
        public string line_no { get; set; }
        public string bom_no { get; set; }
        public string lct_cd { get; set; }
        public string order_sts_cd { get; set; }
        public string plan_start_dt { get; set; }
        public string plan_end_dt { get; set; }
        public Nullable<int> fo_qty { get; set; }
        public string re_mark { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public Nullable<System.DateTime> reg_dt { get; set; }
        public string chg_id { get; set; }
        public Nullable<System.DateTime> chg_dt { get; set; }
    }
}
