//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_info
    {
        public int spno { get; set; }
        public string sp_cd { get; set; }
        public string sp_nm { get; set; }
        public string smt_nm { get; set; }
        public string currency { get; set; }
        public string pirce_term { get; set; }
        public string pay_term { get; set; }
        public string agent_fee { get; set; }
        public string transit_time { get; set; }
        public string e_mail { get; set; }
        public string contact_person { get; set; }
        public string address { get; set; }
        public string country_nm { get; set; }
        public string bsn_tp { get; set; }
        public string changer_id { get; set; }
        public string phone_nb { get; set; }
        public string cell_nb { get; set; }
        public string fax_nb { get; set; }
        public string web_site { get; set; }
        public string re_mark { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
