//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_box_public
    {
        public int bpno { get; set; }
        public string bp_no { get; set; }
        public string bp_name { get; set; }
        public string style_no { get; set; }
        public string ltype_cd { get; set; }
        public Nullable<int> lbox_qty { get; set; }
        public Nullable<int> sbox_qty { get; set; }
        public Nullable<int> prd_qty { get; set; }
        public string bp_sts_cd { get; set; }
        public string bp_dt { get; set; }
        public string re_mark { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
