//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_enviro_hist
    {
        public int ehid { get; set; }
        public string e_no { get; set; }
        public string eh_dt { get; set; }
        public string eh_sts { get; set; }
        public string vol_val { get; set; }
        public string temp_val { get; set; }
        public string motion_val { get; set; }
        public string smoke_val { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
