//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_lbox_hist
    {
        public int lhno { get; set; }
        public string ltype_cd { get; set; }
        public string l_no { get; set; }
        public string style_no { get; set; }
        public string bp_no { get; set; }
        public string qrcode { get; set; }
        public Nullable<int> s_cnt { get; set; }
        public string s_yn { get; set; }
        public Nullable<int> prd_qty { get; set; }
        public Nullable<int> prd_mapping_qty { get; set; }
        public string sts_cd { get; set; }
        public string lct_cd { get; set; }
        public string lct_sts_cd { get; set; }
        public string from_lct_cd { get; set; }
        public string to_lct_cd { get; set; }
        public string charge_id { get; set; }
        public string receive_id { get; set; }
        public string output_dt { get; set; }
        public string input_dt { get; set; }
        public string receive_yn { get; set; }
        public string re_mark { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
