//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_material_map_mc
    {
        public int wmmmid { get; set; }
        public string mt_lot { get; set; }
        public string mt_no { get; set; }
        public string prounit_cd { get; set; }
        public string mc_type { get; set; }
        public string mc_no { get; set; }
        public string mapping_dt { get; set; }
        public string start_dt { get; set; }
        public string end_dt { get; set; }
        public string remark { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public Nullable<System.DateTime> reg_dt { get; set; }
        public string chg_id { get; set; }
        public Nullable<System.DateTime> chg_dt { get; set; }
    }
}
