//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_material_lct_hist
    {
        public int wmlid { get; set; }
        public Nullable<int> pdid { get; set; }
        public string mt_cd { get; set; }
        public string mt_no { get; set; }
        public string lot_div_cd { get; set; }
        public string bbmp_sts_cd { get; set; }
        public string mpo_no { get; set; }
        public string prounit_cd { get; set; }
        public string gr_qty { get; set; }
        public string mdpo_no { get; set; }
        public string date { get; set; }
        public string mt_barcode { get; set; }
        public string mt_sts_cd { get; set; }
        public string bb_no { get; set; }
        public string lct_cd { get; set; }
        public string lct_sts_cd { get; set; }
        public string from_lct_cd { get; set; }
        public string to_lct_cd { get; set; }
        public string output_dt { get; set; }
        public string input_dt { get; set; }
        public string worker_id { get; set; }
        public string sd_no { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public Nullable<System.DateTime> reg_dt { get; set; }
        public string chg_id { get; set; }
        public Nullable<System.DateTime> chg_dt { get; set; }
    }
}
