//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_product_info
    {
        public int pno { get; set; }
        public string l_no { get; set; }
        public string s_no { get; set; }
        public string prd_lcd { get; set; }
        public string prd_cd { get; set; }
        public string buyer_qr { get; set; }
        public int gr_qty { get; set; }
        public string lot_div_cd { get; set; }
        public string style_no { get; set; }
        public string fo_no { get; set; }
        public string po_no { get; set; }
        public string ship_no { get; set; }
        public string bom_no { get; set; }
        public string line_no { get; set; }
        public string prounit_cd { get; set; }
        public string prd_dt { get; set; }
        public string barcode { get; set; }
        public string qrcode { get; set; }
        public string sts_cd { get; set; }
        public string reason_cd { get; set; }
        public string div_cd { get; set; }
        public string bb_no { get; set; }
        public string bb_sts_cd { get; set; }
        public string bx_no { get; set; }
        public string lct_cd { get; set; }
        public string lct_sts_cd { get; set; }
        public string from_lct_cd { get; set; }
        public string to_lct_cd { get; set; }
        public string charge_id { get; set; }
        public string receive_id { get; set; }
        public string output_dt { get; set; }
        public string input_dt { get; set; }
        public string return_yn { get; set; }
        public string return_cd { get; set; }
        public string barcode_yn { get; set; }
        public string qrcode_yn { get; set; }
        public Nullable<int> prd_qty { get; set; }
        public Nullable<int> check_qty { get; set; }
        public Nullable<int> think_def_qty { get; set; }
        public Nullable<int> visual_def_qty { get; set; }
        public string insp_yn { get; set; }
        public string re_mark { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
