//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_product_mapping
    {
        public int pmno { get; set; }
        public string prd_lcd { get; set; }
        public string mt_cd { get; set; }
        public string mt_no { get; set; }
        public string m_div_cd { get; set; }
        public string lot_div_cd { get; set; }
        public string gr_qty { get; set; }
        public string mapping_dt { get; set; }
        public string re_mark { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
