//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_product_inspect
    {
        public int pino { get; set; }
        public string pi_no { get; set; }
        public string prd_lcd { get; set; }
        public string ti_cd { get; set; }
        public string work_dt { get; set; }
        public Nullable<int> total_qty { get; set; }
        public Nullable<int> ok_qty { get; set; }
        public Nullable<int> defect_qty { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
