//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_product_inspect_value
    {
        public int pivno { get; set; }
        public string piv_no { get; set; }
        public string pi_no { get; set; }
        public string ti_cd { get; set; }
        public string tid_cd { get; set; }
        public Nullable<int> check_qty { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
