//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_psdpd_list
    {
        public int psdpid { get; set; }
        public string psdp_no { get; set; }
        public string psd_no { get; set; }
        public string style_no { get; set; }
        public string l_no { get; set; }
        public string prd_lcd { get; set; }
        public string psdp_sts_cd { get; set; }
        public string last_yn { get; set; }
        public string reg_id { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public Nullable<System.DateTime> reg_dt { get; set; }
        public string chg_id { get; set; }
        public Nullable<System.DateTime> chg_dt { get; set; }
    }
}
