//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_pvt_dt
    {
        public int pvdno { get; set; }
        public string pvn_cd { get; set; }
        public string qrcode { get; set; }
        public string lct_cd { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
    }
}
