//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_sdmt_list
    {
        public int sdmid { get; set; }
        public string sdm_no { get; set; }
        public string sd_no { get; set; }
        public string mt_no { get; set; }
        public string mt_cd { get; set; }
        public string smdt_sts_cd { get; set; }
        public string worker { get; set; }
        public string work_dt { get; set; }
        public string last_yn { get; set; }
        public string reg_id { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public Nullable<System.DateTime> reg_dt { get; set; }
        public string chg_id { get; set; }
        public Nullable<System.DateTime> chg_dt { get; set; }
    }
}
