//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_sd_info
    {
        public int sid { get; set; }
        public string sd_no { get; set; }
        public string sd_sts_cd { get; set; }
        public string div_cd { get; set; }
        public string lct_cd { get; set; }
        public string worker_id { get; set; }
        public string manager_id { get; set; }
        public string work_dt { get; set; }
        public string real_work_dt { get; set; }
        public string confirm_dt { get; set; }
        public Nullable<int> mt_qty { get; set; }
        public string mr_no { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string sd_qr_code { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
        public string remark { get; set; }
        public string waybill_file { get; set; }
    }
}
