//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPSYNCSNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_worktime_ymd
    {
        public int wtid { get; set; }
        public string prounit_cd { get; set; }
        public string line_cd { get; set; }
        public string date_ym { get; set; }
        public string date_ymd { get; set; }
        public string date_d { get; set; }
        public Nullable<int> week_n { get; set; }
        public string week { get; set; }
        public string policy_code { get; set; }
        public Nullable<decimal> work_time { get; set; }
        public string work_sts { get; set; }
        public string prod_yn { get; set; }
    }
}
